name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # Verify that snake.svg was generated
      - name: Verify snake.svg exists
        run: |
          if [ ! -f dist/snake.svg ]; then
            echo "Error: snake.svg not found in dist directory!"
            exit 1
          fi

      # List files in dist directory for debugging
      - name: List files in dist
        if: always()  # Ensure this step always runs
        run: |
          if [ -d dist ]; then
            ls -la dist
          else
            echo "Error: dist directory not found!"
            exit 1
          fi

      # Push the generated snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
